### PR TITLE
Use temporary stations when a train stop is limited

### LINKED ISSUE #20: [Suspected issue] Train limits cause crashes
I'm not sure if this is an actual issue or not. I'm pretty sure it is but also too tired to check into it much tonight.

I _think_ that if a train has a station reserved via the new station limiting mechanism, and it jumps, the reservation isn't immediately released. At that point, the loco stops dead, since it can't get to any station, and the following cars land on top of it.

This is just an anecdotal observation from playing on 1.1 - haven't tested it yet.

### PR DESCRIPTION
**Pull request by Xcelled**
Resolves #20 by adding a temporary station to the train if the destination station is limited. Removes the temporary station after the train has landed.

Note that there is a possibility that the train will be unable to path to the station after we remove the temporary station. This happens because a second train could claim the reservation held by the first train while it is in the air. I might have a way around that, but for right now, the jumped train will stop dead immediately after landing until the destination becomes freed up.

Edit: Station reservation is now preserved on a best-effort basis while the train is in the air.

### CODE REVIEW

**Comment by Kiplacon** [comment]
What's up, sorry I couldn't reply to this earlier. I hope you had a good Thanksgiving if you celebrate that where you are. The new train reservation mechanic seems pretty useful, it sucks that it messes up the ramps though. It looks like you already put a lot of  thought into this though and I know you write good stuff, you definitely have more programming experience than me so I'm glad to have your input and support 😃. I'll read through to  try and understand your fix

**Comment by Xcelled** [comment]
My holiday was nice and quiet :)

Yeah, my day job is arguing with computers so I'm used to it haha

I have selfish motivations for fixing issues: my latest save is a game that relies on ramps and stuff and I'm trying to ease it up to megabase level :joy: Let me know if you have questions/concerns

File: script/trains/on_tick.lua [hunk 1]
```diff
@@ -1,5 +1,60 @@
 local Animation = require("animation")
 
+local temporaryPathingCondition = {
+	type = "item_count",
+	compare_type = "and",
+	condition = {
+		comparator = "=",
+	  	first_signal = {type="item", name="RTPropCarItem" },
+		constant = 69
```
Comment (Kiplacon) [inline script/trains/on_tick.lua:9]: nice

**Comment by Kiplacon** [comment]
Good to hear you had a nice break. I work in manufacturing so you're definitely the expert in best practices here. Is there a reason you make so many local variables instead of putting the data in the code where it's used? I find it's easier for me to remember what everything does if it's all right there instead of having to go back and reference a name.

I haven't tried the new station limiting mechanic myself, but it just prevents trains from adding the station as a destination if there are already X number of trains heading towards it? So if I understand your change right it's like this:
- When a train hits a ramp, it checks if its destination station uses train reservation
- If it does, the train presumably has one of those reservations, so you lower the limit by 1 to reserve the train's reservation
- When the train lands, you add a temporary stop right at the station so it keeps moving towards it
- Once all the carriages land, increase the station limit by 1 then remove the temporary stop and send the train to the station so it takes the new reservation spot.

In theory that seems to fix all the problems with station limits 😀. I don't see any problems with it. Have you tried any manual mode jumps or cases where the front of the train jumps again before the rest of the carriages land (a rare edge case) with these changes in?

**Comment by Xcelled** [comment]
I haven't tested any manual cases or weirdness where the train jumps several times at once, but I believe it should work fine in those cases.

There are two reasons I tend to split things up using locals and functions. The first one is called Don't Repeat Yourself (DRY). It's pretty much exactly what it sounds like, in that it's generally better to define something in only one place. This makes it easier to change later, since you don't have to go chasing things all over the codebase and risk forgetting something.

The second reason is a concept called "separation of concerns", which essentially states that the fewer things a bit of code is responsible for, the better. By wrapping small bits of code into functions, you're "abstracting" it away. The goal is that whatever is calling that function shouldn't need to care how it actually does its work. It frees the caller from worrying about implementation details, which in turn simplifies the caller and what's required to understand how it works. And the simpler a bit of code is, the more likely it is to be bug free :)

There's nuance involved, and knowing when and where to split things is an acquired skill. The goal is to design the software so it's made up of small, discrete units that do one or two (simple) things only, then you hook those all together. If you over-split, you end up with your program's logic being completely obfuscated because the logic to do a single discrete operation is spread out all over. But if you undersplit, you end up with [the blob](https://sourcemaking.com/antipatterns/the-blob) or a [big ball of mud](https://en.wikipedia.org/wiki/Big_ball_of_mud).

As you observed, with increased use of functions tends to come with a loss of "locality", essentially what you said about having to go and reference other parts of the code. That's a trade-off that has to be considered when splitting as well. Usually, this is mitigated by using descriptive names, so that the person reading the code has a good idea of what that particular referenced bit is/does without needing to know exactly how it's defined. For times when you do need to know what something is, a good IDE (integrated development environment) is indispensable. For example, I use Visual Studio Code, and if I want to know what something is, I can put my cursor on it and either press f12 to jump to where it's defined or ctrl-shift-f10 to get a popup that shows me the definition without actually moving the cursor there. As an example, I did that with my mouse on `finalizeLandedTrain` and this is what it looks like:

image

Most IDEs have these features (and many more besides) which help immensely when working with code.

That's probably way more information than you wanted, but hopefully that answers your question? I'm happy to explain things further and answer any other questions you have. Software's been my passion for a long time now and I enjoy teaching and explaining it :)

**Comment by Kiplacon** [comment]
I'll test some different setups with your changes, mainly manual mode and temporary stops. Chain jumps I don't think comes up much in actual ramp setups.

I can see you like programming a lot and I appreciate you taking the time to write all that for me 😁. I can see how writing the code like that reduces the chance of errors and keep things consistent, if you're able to keep all the names organized in your head. Being able to jump between labels would definitely help navigation, I didn't know programs could do that. Is there something that can view a program as something like a flow chart? Seeing the mod as a whole with all the connections would be pretty cool.

**Comment by Xcelled** [comment]
> I can see how writing the code like that reduces the chance of errors and keep things consistent, if you're able to keep all the names organized in your head. Being able to jump between labels would definitely help navigation, I didn't know programs could do that. Is there something that can view a program as something like a flow chart? Seeing the mod as a whole with all the connections would be pretty cool.

The goal (though it's notoriously hard to achieve) is to have the names be descriptive enough that anyone reading the code can know what they mean/do without having to keep it all in their head. But naming things concisely yet clearly is hard!

There are programs that can do that sort of flowchart visualization, though IMO it's not actually very useful in practice - mostly because with a program that does anything more than "hello", the flowchart would become so big and complicated as to become unreadable. Flowcharts are often instead used for small bits of a program (no pun intended) or as a very overarching general flow, without regard to details.

That said, there are some programming languages out there that are based completely on flow diagrams, but they tend to be fairly niche. I had a LEGO mindstorms robot as a kid and that was programmed with flow charts.


<details>
<summary>
This is a bit of an extreme example, but this is a flow chart of part of a program.
</summary>
The flow chart was generated by a program called IDA after reading a binary .exe file. The text in each box is the actual "CPU instructions"  of the program. It's a format that's intended to be "read" and executed by the CPU, and so it's missing a lot of the "higher level" things that make code human readable, like variable names and block-style flow control.



If you're curious, the bottom-left block tells the cpu to the following:
 - Put the value 0x8880 into register (ie variable) 6 
- Add the value in register 12 to the value in register 6 and store the result back in register 6
- Treat the value in register 6 as a memory address. Load the value at that memory address and store it in register 12
- Compare the value of register 12 with the value of 0x240.
- Based on the comparison, jump to some other part of the program and start executing the code there.

No, I have no idea what it's trying to achieve lol
</details>
